#!/usr/bin/env perl
# Builds assets/stac-chat-data.js from the approved chatbot content.
#   Answers (EN + NL):          content/chatbot-faq.md   ("**N. Question**" + "- **EN:**" / "- **NL:**")
#   Dutch question + keywords:  content/chatbot-keywords.tsv
# In an answer, "\n" starts a new line in the chat bubble.
# Run from the project folder:   perl tools/build-chat-data.pl
use strict; use warnings; use utf8;
use open qw(:std :utf8);

my ($md_path, $kw_path, $out_path) = ('content/chatbot-faq.md', 'content/chatbot-keywords.tsv', 'assets/stac-chat-data.js');

my %kw;
open my $k, '<', $kw_path or die "Can't read $kw_path: $!\n";
while (<$k>) {
  s/\r?\n//; next if !length || /^#/;
  my ($id, $qnl, $words, $pref) = split /\t/;
  $kw{$id} = [$qnl, $words // '', ($pref // '') =~ /^\d+$/ ? $pref : 0];
}

open my $m, '<', $md_path or die "Can't read $md_path: $!\n";
my ($cat, @rows) = ('');
while (<$m>) {
  s/\r?\n//;
  if (/^## ([A-Z])\. /) { $cat = $1; next; }
  if (/^\*\*(\d+)\. (.+?)\*\*$/) { push @rows, { id => $1, cat => $cat, q => $2 }; next; }
  next unless @rows;
  if (/^- \*\*EN:\*\* (.+)$/ && !$rows[-1]{en}) { $rows[-1]{en} = $1; next; }
  if (/^- \*\*NL:\*\* (.+)$/ && !$rows[-1]{nl}) { $rows[-1]{nl} = $1; next; }
}

sub js {
  my $s = shift;
  $s =~ s/&amp;/&/g;
  $s =~ s/\\/\\\\/g; $s =~ s/"/\\"/g;
  $s =~ s/\\\\n/\\n/g;          # keep the "\n" line breaks as real newlines in JS
  return qq{"$s"};
}

my @out;
for my $r (@rows) {
  die "Answer $r->{id} is missing its EN or NL text in $md_path\n" unless $r->{en} && $r->{nl};
  die "Answer $r->{id} has no line in $kw_path (Dutch question + keywords)\n" unless $kw{$r->{id}};
  push @out, "  {id:$r->{id},cat:" . js($r->{cat}) . ",q:{en:" . js($r->{q}) . ",nl:" . js($kw{$r->{id}}[0]) .
             "},a:{en:" . js($r->{en}) . ",nl:" . js($r->{nl}) . "},k:" . js($kw{$r->{id}}[1]) .
             ($kw{$r->{id}}[2] ? ",p:$kw{$r->{id}}[2]" : "") . "}";
}

open my $o, '>', $out_path or die "Can't write $out_path: $!\n";
print $o "/* STAC chat assistant: approved answers (source: content/chatbot-faq.md + content/chatbot-keywords.tsv).\n" .
         "   Generated by tools/build-chat-data.pl - edit those files, then run: perl tools/build-chat-data.pl */\n" .
         "window.STAC_CHAT_DATA=[\n" . join(",\n", @out) . "\n];\n";
print scalar(@out) . " answers written to $out_path\n";
